### ISSUE TITLE
Add topgrade

### ISSUE THREAD

**Issue by philclifford** [OhMyMndy/bin-get#3]
See https://github.com/wimpysworld/deb-get/issues/276 
I'll take a look at adding a PR for it once I figure out the testing.

**Comment by OhMyMndy** [comment]
Added support for topgrade:
https://github.com/OhMyMndy/bin-get/runs/7388626500?check_suite_focus=true
https://github.com/OhMyMndy/bin-get/commit/486292ad53c0c6b94ef980a639ed582a7870f401
